name: user_repository
description: A new Flutter package project.
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  equatable: ^2.0.5
  uuid: ^3.0.7

dev_dependencies:
  very_good_analysis: ^3.1.0
