name: todos_api
description: The interface and models for an API providing access to todos.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  meta: ^1.8.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.2
  coverage: ^1.1.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.22.0
  very_good_analysis: ^3.0.0
